version: '3.6'

services:
    
    mqtt:
        container_name: mqtt
        build: ./mqtt/
        ports:
            - '1883:1883'
        volumes:
            - './mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf'
        restart: always

    influxdb:
        container_name: influxdb
        image: hypriot/rpi-influxdb:latest
        ports:
            - '8086:8086'
        volumes:
            - ./influxdb/data:/data
            - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
        env_file: 
            - ./.env
        environment:
            - ADMIN_USER=${INFLUXDB_USERNAME} # sourced from .env
            - INFLUXDB_INIT_PWD=${INFLUXDB_PASSWORD} # sourced from .env
            - PRE_CREATE_DB='CREATE DATABASE sensors'    
        restart: always

    grafana:
        container_name: grafana
        image: grafana/grafana
        volumes: 
            - ./grafana/grafana.ini:/etc/grafana/grafana.ini
            - ./grafana/data:/var/lib/grafana
        ports:
            - '3000:3000'
        user: root

    node-exporter:
        container_name: node-exporter
        image: prom/node-exporter:latest
        ports:
            - '9100:9100'
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        restart: always

    prometheus:
        container_name: prometheus
        image: prom/prometheus:latest
        ports:
            - '9090:9090'
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
        restart: always
        user: root