version: '3.6'

services:

    mqtt:
        container_name: mqtt
        build: ./mqtt/
        ports:
            - '9001:9001'
            - '1883:1883'
        volumes:
            - './mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf'
        restart: on-failure

    influxdb:
        container_name: influxdb
        image: hypriot/rpi-influxdb:latest
        ports:
            - '8083:8083'
            - '8086:8086'
            - '8090:8090'
        volumes:
            - ./influxdb/data:/data
            - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
        env_file: 
            - ./.env
        environment:
            - ADMIN_USER=${INFLUXDB_USERNAME} # sourced from .env
            - INFLUXDB_INIT_PWD=${INFLUXDB_PASSWORD} # sourced from .env
            - PRE_CREATE_DB='CREATE DATABASE sensors'    
        restart: on-failure

    # chronograf: # influxdb admin UI
    #     container_name: chronograf
    #     image: chronograf
    #     ports:
    #         - '8888:8888'
    #     restart: on-failure
    #     environment: 
    #         - INFLUXDB_URL=http://influxdb:8086 # needs to match container_name
    #         - INFLUXDB_USERNAME=${INFLUXDB_USERNAME} # sourced from .env
    #         - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD} # sourced from .env
    #     depends_on: 
    #         - influxdb

    # telegraf: # consider telegraf cpu/mem monitoring..
    #     container_name: telegraf
    #     image: telegraf
    #     ports:
    #         - '8092:8092'
    #         - '8094:8094'
    #         - '8125:8125'
    #     volumes: 
    #         - './telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro'
    #     restart: on-failure

    # grafana:
    #     container_name: grafana
    #     image: grafana/grafana
    #     ports:
    #         - '3000:3000'
